workflows:
  expo_android_local:
    name: Expo -> Android (APK local)
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      node: 18
      java: 17
      vars:
        ANDROID_HOME: /opt/android-sdk-linux
    cache:
      cache_paths:
        - ~/.npm
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    scripts:
      - name: Instalar dependencias
        script: |
          npm ci || npm install
      - name: Prebuild de Expo a proyecto nativo Android
        script: |
          npx expo prebuild --platform android --non-interactive
      - name: Compilar APK (debug)
        script: |
          cd android
          ./gradlew assembleDebug
          mkdir -p ../build
          cp app/build/outputs/apk/debug/app-debug.apk ../build/AgendaParaBienestar-debug.apk
    artifacts:
      - build/*.apk
