workflows:
  expo_android_local:
    name: "Expo -> Android (APK local)"
    instance_type: linux_x2
    max_build_duration: 60

    environment:
      node: 18
      java: 17
      vars:
        CI: "1"

    cache:
      cache_paths:
        - ~/.npm
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Verificar archivos y versiones
        script: |
          echo "Listado raíz del repo:"
          ls -la
          echo "Node:"
          node -v
          echo "Java:"
          java -version
          if [ ! -f package.json ]; then
            echo "FALTA package.json en la raíz del repo"; exit 1
          fi

      - name: Instalar Expo CLI y dependencias
        script: |
          npm ci || npm install --no-audit --no-fund
          npm install -g expo-cli

      - name: Prebuild de Expo a Android
        script: |
          npx expo --version
          npx expo prebuild --platform android --non-interactive

      - name: Compilar APK (debug)
        script: |
          cd android
          ./gradlew assembleDebug
          mkdir -p ../build
          cp app/build/outputs/apk/debug/app-debug.apk ../build/AgendaParaBienestar-debug.apk

    artifacts:
      - build/*.apk
