workflows:
  android_debug_apk:
    name: Build React Native Android (Debug APK)
    instance_type: linux
    max_build_duration: 60
    environment:
      node: 18
      java: 17
      vars:
        ANDROID_HOME: /opt/android-sdk-linux
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - ~/.npm
        - ~/.cache/yarn
    scripts:
      - name: Instalar dependencias Node
        script: |
          npm ci || npm install
      - name: Aceptar licencias del SDK de Android
        script: |
          yes | sdkmanager --licenses || true
      - name: Preparar Gradle
        script: |
          cd android
          ./gradlew tasks
      - name: Compilar APK Debug (instalable)
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
