workflows:
  expo_android_apk:
    name: Build Expo → Android (APK local)
    instance_type: linux
    max_build_duration: 60

    environment:
      node: 18
      java: 17
      vars:
        ANDROID_HOME: /opt/android-sdk-linux

    cache:
      cache_paths:
        - ~/.npm
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    triggering:
      events:
        - manual
      branch_patterns:
        - pattern: principal
          include: true
          source: true

    scripts:
      - name: Verificar entorno
        script: |
          echo "Node: $(node -v)"
          echo "Java:"
          java -version
          echo "ANDROID_HOME=$ANDROID_HOME"

      - name: Aceptar licencias de Android SDK
        script: |
          yes | "$ANDROID_HOME/tools/bin/sdkmanager" --licenses || true

      - name: Instalar dependencias
        script: |
          npm ci || npm install

      - name: Prebuild de Expo para Android
        script: |
          npx expo --version || npx --yes expo@latest --version
          # Genera carpeta /android a partir de app.json/app.config.* 
          npx expo prebuild --platform android --non-interactive --clean

      - name: Dar permisos a Gradle wrapper
        script: |
          chmod +x android/gradlew

      - name: Compilar APK Release
        script: |
          cd android
          ./gradlew assembleRelease

      - name: Copiar APK a artefactos
        script: |
          mkdir -p "$CM_ARTIFACTS"
          ls -la app/build/outputs/apk/release/ || true
          cp app/build/outputs/apk/release/app-release.apk "$CM_ARTIFACTS/app-release.apk"

    artifacts:
      - $CM_ARTIFACTS/app-release.apk
