workflows:
  expo_android_local:
    name: "Expo → Android (APK local)"
    max_build_duration: 60
    instance_type: linux_x2   # GRATIS. No uses mac_mini_m1
    environment:
      flutter: none
      node: 18
      java: 17
      xcode: none
      vars:
        CI: "1"
    cache:
      cache_paths:
        - ~/.npm
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Verificar archivos y Node
        script: |
          echo "Contenido de la raíz:"
          ls -la
          node -v
          test -f package.json || (echo "FALTA package.json en la raíz" && exit 1)

      - name: Instalar Expo CLI y dependencias
        script: |
          npm ci || npm install
          npm install -g expo-cli

      - name: Prebuild de Expo a Android
        script: |
          npx expo --version
          npx expo prebuild --platform android --non-interactive

      - name: Compilar APK (debug)
        script: |
          cd android
          ./gradlew assembleDebug
          mkdir -p ../build
          cp app/build/outputs/apk/debug/app-debug.apk ../build/AgendaParaBienestar-debug.apk

    artifacts:
      - build/*.apk
