workflows:
  react_native_app:
    name: Build React Native Android (APK)
    environment:
      node: 18
      java: 17
    scripts:
      - name: Instalar dependencias
        script: |
          npm install
      - name: Compilar APK con EAS
        script: |
          npx expo install
          npx eas build --platform android --profile preview --local --output ./app-release.apk
    artifacts:
      - app-release.apk
