workflows:
  expo_eas_android:
    name: Build Expo (EAS) Android
    instance_type: linux
    max_build_duration: 60
    environment:
      node: 18
      vars:
        EAS_NO_VCS: "1"
    cache:
      cache_paths:
        - ~/.npm
        - ~/.cache/eas
    scripts:
      - name: Instalar dependencias
        script: |
          npm ci || npm install
      - name: Ver versión de Expo y EAS
        script: |
          npx expo --version
          npx eas --version
      - name: Login opcional a Expo (usa variables si las configuras)
        script: |
          if [ -n "$EXPO_TOKEN" ]; then
            npx expo whoami || true
          fi
      - name: Compilar Android (preview)
        script: |
          npx eas build -p android --profile preview --non-interactive
    artifacts:
      - ./build/**/*
