workflows:
  expo_android_local:
    name: Expo -> Android (APK local)
    instance_type: linux_x2
    max_build_duration: 60

    environment:
      node: 18
      java: 17
      vars:
        CI: "1"
        EXPO_NO_TELEMETRY: "1"

    cache:
      cache_paths:
        - ~/.npm
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Verificar archivos y versión de Node
        script: |
          echo "Listado de raíz:"
          ls -la
          echo "Node:"
          node -v
          if [ ! -f package.json ]; then
            echo "FALTA package.json en la raíz del repo"; exit 1;
          fi

      - name: Limpiar instalación previa (idempotente)
        script: |
          rm -rf node_modules android build || true
          rm -f yarn.lock # usamos npm
          npm cache verify

      - name: Instalar dependencias del proyecto
        script: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi

      # IMPORTANTE: no instalar manualmente expo-modules-autolinking NI @expo/prebuild-config

      - name: Prebuild de Expo a Android (limpio)
        script: |
          npx expo --version
          npx expo prebuild --platform android --non-interactive --clean

      - name: Compilar APK (debug)
        script: |
          cd android
          ./gradlew assembleDebug
          mkdir -p ../build
          cp app/build/outputs/apk/debug/app-debug.apk ../build/AgendaParaBienestar-debug.apk

    artifacts:
      - build/*.apk
