name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Unzip project
        run: |
          mkdir -p src
          ZIP_FILE="$(ls -1 | grep -E '^AgendaBienestarProyect.*\.zip$' | head -n 1 || true)"
          if [ -z "$ZIP_FILE" ]; then
            echo "No se encontró un ZIP que empiece con 'AgendaBienestarProyect'."
            exit 1
          fi
          echo "Usando ZIP: $ZIP_FILE"
          unzip -q "$ZIP_FILE" -d src
          echo "Contenido de src/"
          find src -maxdepth 3 -type f | sed 's/^/  /'

      - name: Locate project dir (settings.gradle)
        id: locate
        shell: bash
        run: |
          set -e
          SETTINGS_PATH="$(find src -type f -name 'settings.gradle' -print -quit || true)"
          if [ -z "$SETTINGS_PATH" ]; then
            echo "No se encontró settings.gradle dentro del ZIP."
            exit 1
          fi
          PROJECT_DIR="$(dirname "$SETTINGS_PATH")"
          echo "PROJECT_DIR=$PROJECT_DIR" | tee -a "$GITHUB_ENV"
          echo "Proyecto detectado en: $PROJECT_DIR"
          echo "Listado del proyecto:"
          ls -la "$PROJECT_DIR"

      # Si no hay gradlew, instala Gradle para poder compilar
      - name: Ensure Gradle available
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.6

      - name: Build APK
        run: |
          cd "$PROJECT_DIR"
          if [ -f gradlew ]; then
            echo "Usando Gradle Wrapper"
            chmod +x gradlew
            ./gradlew --no-daemon :app:assembleDebug
          else
            echo "No hay gradlew; usando Gradle instalado"
            gradle --no-daemon :app:assembleDebug
          fi

      - name: Collect APKs
        id: collect
        run: |
          APK_DIR="$PROJECT_DIR/app/build/outputs/apk"
          echo "Buscando APKs en: $APK_DIR"
          find "$APK_DIR" -type f -name "*.apk" -print > apk_list.txt || true
          cat apk_list.txt
          COUNT=$(wc -l < apk_list.txt | tr -d ' ')
          if [ "$COUNT" -eq 0 ]; then
            echo "No se encontró ningún APK."
            exit 1
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-apks
          path: |
            $(cat apk_list.txt)
