name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 1) Descomprimir el ZIP más reciente al folder src/
      - name: Unzip project
        run: |
          set -e
          ZIP="$(ls -1t *.zip | head -n 1)"
          echo "ZIP file: $ZIP"
          test -n "$ZIP"
          rm -rf src
          mkdir -p src
          unzip -q "$ZIP" -d src
          echo "Root of src:"
          ls -la src

      # 2) Instalar Gradle para poder GENERAR el wrapper
      - name: Install Gradle (to generate wrapper)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gradle
          gradle --version

      # 3) Generar gradle wrapper dentro del runner
      - name: Generate Gradle wrapper
        working-directory: src
        run: |
          # Debe haber build.gradle y settings.gradle en src/
          test -f build.gradle || (echo "No existe build.gradle en src/"; exit 1)
          gradle wrapper
          ls -la
          ls -la gradle/wrapper || true

      # 4) Compilar con el wrapper recién generado
      - name: Build APK (assembleDebug)
        working-directory: src
        run: |
          chmod +x ./gradlew
          ./gradlew -p app assembleDebug

      # 5) Recopilar y publicar APKs
      - name: Collect APKs
        if: always()
        run: |
          mkdir -p apk_out
          find src/app/build/outputs/apk -type f -name "*.apk" -print -exec cp {} apk_out/ \; || true
          ls -la apk_out || true

      - name: Upload APK artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-apks
          path: apk_out/*
          if-no-files-found: warn
