name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Obtener el repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Detectar la carpeta del proyecto (donde está gradlew)
      #    Si no encuentra, usa la raíz "."
      - name: Detect project directory
        id: findproj
        shell: bash
        run: |
          set -e
          HIT="$(git ls-files | grep -m1 -E '(^|/)gradlew$' || true)"
          if [ -n "$HIT" ]; then
            PROJ_DIR="$(dirname "$HIT")"
            # si gradlew está en la raíz, dirname devuelve "."
            echo "proj_dir=$PROJ_DIR" >> "$GITHUB_OUTPUT"
          else
            echo "⚠️  No se encontró gradlew. Se usará la raíz del repo."
            echo "proj_dir=." >> "$GITHUB_OUTPUT"
          fi
          echo "Proyecto en: $PROJ_DIR"

      # 3) Asegurar permisos de ejecución al gradlew
      - name: Make gradlew executable
        if: always()
        run: chmod +x gradlew || true
        working-directory: ${{ steps.findproj.outputs.proj_dir }}

      # 4) JDK 17 (recomendado por Android Gradle Plugin)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 5) Instalar Android SDK y paquetes esenciales
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0

      # 6) Cache de Gradle (acelera reconstrucciones)
      - name: Prepare Gradle (cache)
        uses: gradle/actions/setup-gradle@v3

      # 7) Compilar APK Debug
      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug --stacktrace --warning-mode=all --no-daemon
        working-directory: ${{ steps.findproj.outputs.proj_dir }}

      # 8) Subir el APK como artefacto descargable
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: ${{ steps.findproj.outputs.proj_dir }}/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
