name: Build Android APK

on:
  workflow_dispatch:

env:
  PROJECT_DIR: AgendaBienestarProyecto     # <-- carpeta donde está tu proyecto Android

jobs:
  build:
    runs-on: ubuntu-latest

    # todos los "run:" se ejecutan dentro de la carpeta del proyecto
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
          # MUY IMPORTANTE: dile dónde están los archivos de Gradle (subcarpeta)
          cache-dependency-path: |
            ${{ env.PROJECT_DIR }}/**/*.gradle*
            ${{ env.PROJECT_DIR }}/**/gradle-wrapper.properties
            ${{ env.PROJECT_DIR }}/gradle/libs.versions.toml
            ${{ env.PROJECT_DIR }}/**/versions.properties

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # Usaremos Gradle SIN wrapper
      - name: Prepare Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Debug APK (no wrapper)
        run: |
          gradle -p . :app:assembleDebug --stacktrace --warning-mode all --no-daemon

      - name: Find generated APK
        id: find_apk
        run: |
          APK=$(ls -1 "${GITHUB_WORKSPACE}/${{ env.PROJECT_DIR }}/app/build/outputs/apk/debug/"*.apk | head -n 1)
          echo "apk_path=$APK" >> "$GITHUB_OUTPUT"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: ${{ steps.find_apk.outputs.apk_path }}
          if-no-files-found: error
