name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Usamos Gradle sin wrapper local; NO ponemos working-directory aquí
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.6
          # ¡Ruta RELATIVA al repo, sin ${{ github.workspace }}!
          build-root-directory: AgendaBienestarProyecto
          arguments: :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: AgendaBienestarProyecto/app/build/outputs/apk/debug/*.apk
