name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Encuentra y descomprime el ZIP del proyecto (tome el más reciente)
      - name: Unzip project
        run: |
          set -e
          ZIP="$(ls -1t *.zip | head -n 1)"
          echo "ZIP file: $ZIP"
          test -n "$ZIP"
          rm -rf src
          mkdir -p src
          unzip -q "$ZIP" -d src
          echo "Contenido raíz descomprimido:"
          ls -la src

      # Instala Gradle desde apt (evitamos usar gradle wrapper)
      - name: Install Gradle
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gradle
          gradle --version

      # Compila el módulo app en modo debug
      - name: Build APK
        working-directory: src
        run: |
          # Si tu proyecto tiene carpeta "app" dentro de src, esto compila:
          gradle -p app assembleDebug

      # Sube el APK como artefacto
      - name: Collect APKs
        if: always()
        run: |
          mkdir -p apk_out
          find src/app/build/outputs/apk -type f -name "*.apk" -print -exec cp {} apk_out/ \; || true
          ls -la apk_out || true

      - name: Upload APK artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-apks
          path: apk_out/*
          if-no-files-found: warn
