name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Unzip project
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip
          rm -rf src
          unzip -q "AgendaBienestarProyecto.zip" -d src
          echo "Descomprimido en ./src"

      - name: Locate Gradle wrapper
        id: locate
        shell: bash
        run: |
          GRADLEW_PATH="$(find src -type f -name gradlew -print -quit)"
          if [ -z "$GRADLEW_PATH" ]; then
            echo "No se encontró gradlew dentro del ZIP" >&2
            exit 1
          fi
          ROOT_DIR="$(dirname "$GRADLEW_PATH")"
          echo "root=$ROOT_DIR" >> "$GITHUB_OUTPUT"

      - name: Build APK
        run: |
          cd "${{ steps.locate.outputs.root }}"
          chmod +x ./gradlew
          ./gradlew clean assembleDebug

      - name: Collect APKs
        run: |
          mkdir -p "$GITHUB_WORKSPACE/apks"
          find "${{ steps.locate.outputs.root }}" -type f -name "*.apk" -exec cp {} "$GITHUB_WORKSPACE/apks/" \;
          ls -l "$GITHUB_WORKSPACE/apks"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: apks/*.apk
          if-no-files-found: error
