name: Build Android APK (Expo)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Use Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # (Opcional) Cache de NPM para acelerar builds siguientes
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install

      - name: Install Expo CLI
        run: npm i -g expo@^50

      # ✅ Verificación estricta de assets
      - name: Verify assets exist
        run: |
          echo "Listado de archivos en el repo:"
          ls -la
          echo "Listado en ./assets:"
          ls -la assets || true
          for f in assets/icon.png assets/splash.png assets/adaptive-icon.png; do
            if [ ! -f "$f" ]; then
              echo "::error::Falta el archivo requerido: $f"
              exit 1
            fi
            file "$f" || true
          done

      # Genera android/ con Expo (no reinstala deps)
      - name: Expo prebuild (Android)
        env:
          CI: true
        run: npx expo prebuild --platform android --clean --no-install

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build APK (debug)
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Agenda-para-bienestar-debug
          path: android/app/build/outputs/apk/debug/*.apk
