name: Build Android APK (Expo)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Use Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Instalamos sin exigir package-lock.json
      - name: Install dependencies
        run: npm install

      - name: Install Expo CLI
        run: npm i -g expo@^50

      # Genera la carpeta android/ desde un proyecto Expo (managed)
      - name: Expo prebuild (Android)
        run: npx expo prebuild --platform android --clean --no-install

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build APK (debug)
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Agenda-para-bienestar-debug
          path: android/app/build/outputs/apk/debug/*.apk
