name: Build Android APK (Expo)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Install Expo CLI + deps
        run: |
          npm i -g expo-cli
          npm ci --no-audit --no-fund

      - name: Prebuild native Android
        run: |
          npx expo --version
          npx expo prebuild --platform android --non-interactive

      - name: Build APK (debug)
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Collect APK
        run: |
          mkdir -p build
          cp android/app/build/outputs/apk/debug/app-debug.apk build/AgendaParaBienestar-debug.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: AgendaParaBienestar-debug
          path: build/AgendaParaBienestar-debug.apk
          if-no-files-found: error
