name: Build Android APK (Expo)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # ⚠️ SIN package-lock.json usamos "npm install", no "npm ci"
      - name: Install deps
        run: |
          npm install --legacy-peer-deps

      - name: Install Expo CLI
        run: npm i -g expo@latest

      - name: Expo prebuild (Android)
        run: npx expo prebuild --platform android --non-interactive

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build APK (debug)
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
