name: Build Flutter/Android (sin ZIP)

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'   # estable

      # 1) Crear proyecto Flutter vacío en carpeta app/
      - name: Create Flutter project
        run: |
          flutter --version
          flutter create \
            --org com.agenda.bienestar \
            --project-name AgendaBienestar \
            app

      # 2) Sobrescribir el AndroidManifest con tu label e intent-filter (exported)
      - name: Apply AndroidManifest
        run: |
          cat > app/android/app/src/main/AndroidManifest.xml <<'XML'
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="com.agenda.bienestar.agendabienestar">
            <application
                android:label="Agenda para Bienestar"
                android:icon="@mipmap/ic_launcher"
                android:roundIcon="@mipmap/ic_launcher_round"
                android:allowBackup="true"
                android:supportsRtl="true"
                android:usesCleartextTraffic="false">
              <activity
                  android:name=".MainActivity"
                  android:exported="true"
                  android:launchMode="singleTop"
                  android:windowSoftInputMode="adjustResize">
                <intent-filter>
                  <action android:name="android.intent.action.MAIN" />
                  <category android:name="android.intent.category.LAUNCHER" />
                </intent-filter>
              </activity>

              <!-- (Opcional) Si usas AdMob, pon tu APP_ID real -->
              <!--
              <meta-data
                  android:name="com.google.android.gms.ads.APPLICATION_ID"
                  android:value="ca-app-pub-XXXXXXXXXXXXXXXX~XXXXXXXXXX"/>
              -->
            </application>
          </manifest>
          XML

      # 3) Reemplazar lib/main.dart con una pantalla de lista + FAB
      - name: Apply main.dart (lista + FAB)
        run: |
          cat > app/lib/main.dart <<'DART'
          import 'package:flutter/material.dart';

          void main() => runApp(const AgendaApp());

          class AgendaApp extends StatelessWidget {
            const AgendaApp({super.key});

            @override
            Widget build(BuildContext context) {
              return MaterialApp(
                title: 'Agenda para Bienestar',
                theme: ThemeData(
                  useMaterial3: true,
                  colorSchemeSeed: Colors.teal,
                  brightness: Brightness.light,
                ),
                home: const AgendaHomePage(),
              );
            }
          }

          class AgendaHomePage extends StatefulWidget {
            const AgendaHomePage({super.key});

            @override
            State<AgendaHomePage> createState() => _AgendaHomePageState();
          }

          class _AgendaHomePageState extends State<AgendaHomePage> {
            final List<String> _items = [
              'Respirar 5 min',
              'Vaso de agua',
              'Estiramientos'
            ];

            void _addItem() async {
              final controller = TextEditingController();
              final text = await showDialog<String>(
                context: context,
                builder: (ctx) => AlertDialog(
                  title: const Text('Nuevo evento'),
                  content: TextField(
                    controller: controller,
                    autofocus: true,
                    decoration: const InputDecoration(
                      hintText: 'Ej: Caminar 10 min',
                    ),
                  ),
                  actions: [
                    TextButton(
                      onPressed: () => Navigator.pop(ctx),
                      child: const Text('Cancelar'),
                    ),
                    FilledButton(
                      onPressed: () =>
                          Navigator.pop(ctx, controller.text.trim()),
                      child: const Text('Guardar'),
                    ),
                  ],
                ),
              );
              if (text != null && text.isNotEmpty) {
                setState(() => _items.add(text));
              }
            }

            void _removeItem(int index) {
              setState(() => _items.removeAt(index));
            }

            @override
            Widget build(BuildContext context) {
              return Scaffold(
                appBar: AppBar(
                  title: const Text('Agenda de Bienestar'),
                ),
                body: _items.isEmpty
                    ? const Center(
                        child: Text(
                          'Sin eventos. Toca + para agregar uno.',
                          style: TextStyle(fontSize: 16),
                        ),
                      )
                    : ListView.separated(
                        padding: const EdgeInsets.all(12),
                        itemCount: _items.length,
                        separatorBuilder: (_, __) => const SizedBox(height: 8),
                        itemBuilder: (_, i) {
                          return Dismissible(
                            key: ValueKey(_items[i]),
                            direction: DismissDirection.endToStart,
                            onDismissed: (_) => _removeItem(i),
                            background: Container(
                              alignment: Alignment.centerRight,
                              padding: const EdgeInsets.symmetric(horizontal: 16),
                              color: Colors.red.withOpacity(0.2),
                              child: const Icon(Icons.delete),
                            ),
                            child: Card(
                              child: ListTile(
                                title: Text(_items[i]),
                                leading: const Icon(Icons.event_note),
                              ),
                            ),
                          );
                        },
                      ),
                floatingActionButton: FloatingActionButton(
                  onPressed: _addItem,
                  child: const Icon(Icons.add),
                ),
              );
            }
          }
          DART

      - name: Flutter pub get
        working-directory: app
        run: flutter pub get

      - name: Build Android APK (release)
        working-directory: app
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: AgendaBienestar-APK
          path: app/build/app/outputs/flutter-apk/app-release.apk
