<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.agenda.bienestar">

    <application
        android:label="Agenda para Bienestar"
        android:icon="@mipmap/ic_launcher"
        android:allowBackup="true"
        android:supportsRtl="true">

        <!-- Activity principal con intent-filter => requiere exported="true" en Android 12+ -->
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:windowSoftInputMode="adjustResize">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <!-- Si en tu proyecto hay OTROS <activity>, <service> o <receiver> con <intent-filter>,
             también deben tener android:exported="true" o "false" según corresponda. -->
    </application>
</manifest>
