name: Build Flutter Android App

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # o la versión que uses

      - name: Navigate to project directory
        run: cd AgendaBienestarProyecto

      - name: Install dependencies
        working-directory: AgendaBienestarProyecto
        run: flutter pub get

      - name: Build APK
        working-directory: AgendaBienestarProyecto
        run: flutter build apk --release

      - name: Build App Bundle (AAB)
        working-directory: AgendaBienestarProyecto
        run: flutter build appbundle --release

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: AgendaBienestarProyecto/build/app/outputs/bundle/release/*.aab
